### PR TITLE
Feature/reduce-decoder-mem-usage

### PR DESCRIPTION
**Pull request by cathalobrien**
This change increases the memory saved from using chunking in the mapper. At the moment we use two arrays to accumulate chunks, this replaces it with a single array. At 9km this reduces peak memory usage by 6GB. 

Below I have pictures of memory usage during the chunking part of the decoder at 9km
### Before

Screenshot 2024-11-21 at 13 55 24

Notice the zig-zag pattern. This is from the 'out1' tensor being constantly created and freed each chunk.

### After
Screenshot 2024-11-21 at 13 55 37

Now the zig-zag pattern is gone and peak memory usage has decreased by 6GB

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-models?pullRequest=84) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-models?pullRequest=84) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-models?pullRequest=84) it.</sub>

**Comment by cathalobrien** [comment]
> great work. Is this from a training run or inference run?

Inference. Havent tried in training bc this only happens when num_chunks > 1

**Comment by ssmmnn11** [comment]
Absolutely, would be just interesting to check.

**Comment by floriankrb** [comment]
Thanks for this improvement @cathalobrien , please sign the CLA (see above...)

image

**Comment by cathalobrien** [comment]
> Thanks for this improvement @cathalobrien , please sign the CLA (see above...)

done, thanks @floriankrb

**Review by japols — APPROVED** [review]
Looks good, nice catch :)

**Pull request merged**
